spring:
  sql:
    init:
      platform: mysql
      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myDb?serverTimezone=UTC&characterEncoding=UTF-8
    username: testuser
    password: testuser1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    #    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL57Dialect